# Generated by Django 6.0.8 on 2026-08-09 11:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InternshipSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("base_url", models.URLField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_scraped_at", models.DateTimeField(blank=True, null=True)),
                ("total_internships_scraped", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Internship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("company_logo_url", models.URLField(blank=True)),
                ("location", models.CharField(max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                            ("onsite", "Onsite"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("tech", "Tech"),
                            ("marketing", "Marketing"),
                            ("design", "Design"),
                            ("finance", "Finance"),
                            ("data_science", "Data Science"),
                            ("hr", "HR"),
                            ("operations", "Operations"),
                            ("content", "Content"),
                            ("sales", "Sales"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration", models.CharField(blank=True, max_length=50)),
                ("duration_months", models.PositiveIntegerField(blank=True, null=True)),
                ("stipend_min", models.PositiveIntegerField(blank=True, null=True)),
                ("stipend_max", models.PositiveIntegerField(blank=True, null=True)),
                ("stipend_display", models.CharField(blank=True, max_length=100)),
                ("is_unpaid", models.BooleanField(default=False)),
                ("skills_required", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
                ("requirements", models.TextField(blank=True)),
                ("perks", models.JSONField(blank=True, default=list)),
                ("apply_link", models.URLField(max_length=1000)),
                ("source_job_id", models.CharField(max_length=255)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("posted_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internships",
                        to="internships.internshipsource",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_at"],
                "indexes": [
                    models.Index(
                        fields=["domain"], name="internships_domain_c6e6e5_idx"
                    ),
                    models.Index(
                        fields=["work_type"], name="internships_work_ty_59cdcd_idx"
                    ),
                    models.Index(fields=["city"], name="internships_city_2ac0c0_idx"),
                    models.Index(
                        fields=["stipend_min"], name="internships_stipend_cb478c_idx"
                    ),
                    models.Index(
                        fields=["deadline"], name="internships_deadlin_509b56_idx"
                    ),
                    models.Index(
                        fields=["posted_at"], name="internships_posted__93ee10_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="internships_is_acti_1cb43c_idx"
                    ),
                ],
                "unique_together": {("source", "source_job_id")},
            },
        ),
    ]
