# Generated by Django 6.0.8 on 2026-08-17 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="posted_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="internship",
            name="source_job_id",
            field=models.CharField(
                blank=True,
                help_text="The listing's ID on the source platform. Leave blank for a manually-curated internship — one will be generated automatically.",
                max_length=255,
            ),
        ),
    ]
