# Generated by Django 6.0.8 on 2026-08-10 03:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("internships", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("manual_company", models.CharField(blank=True, max_length=255)),
                ("manual_role", models.CharField(blank=True, max_length=255)),
                ("manual_apply_link", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("under_review", "Under Review"),
                            ("interview", "Interview"),
                            ("offer_received", "Offer Received"),
                            ("selected", "Selected"),
                            ("rejected", "Rejected"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("next_step", models.CharField(blank=True, max_length=255)),
                ("reminder_date", models.DateField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "internship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="internships.internship",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="application_user_id_9457c8_idx"
                    ),
                    models.Index(
                        fields=["status"], name="application_status_1508e0_idx"
                    ),
                    models.Index(
                        fields=["applied_at"], name="application_applied_06e426_idx"
                    ),
                ],
            },
        ),
    ]
