# Generated by Django 6.0.8 on 2026-08-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="manual_stipend",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
