# Generated by Django 6.0.8 on 2026-08-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="application_status_alerts_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="deadline_reminders_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_digest",
            field=models.CharField(
                choices=[("daily", "Daily"), ("weekly", "Weekly"), ("never", "Never")],
                default="weekly",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_profile_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="new_matches_alert_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
